# Generated by Django 4.2.4 on 2024-01-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
